# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Streetwear Guides
description: > # this means to ignore newlines until "baseurl:"
  A website dedicated to anyone who wants to learn more about the sect of fashion called Streetwear. Within these pages are guides to brands, aesthetics, colour palettes and different types of garments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://streetwearguides.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
